package com.example.sub2.model

data class League(
	val strDescriptionES: Any? = null,
	val dateFirstEvent: String? = null,
	val intFormedYear: String? = null,
	val strBanner: String? = null,
	val strSport: String? = null,
	val strDescriptionIT: Any? = null,
	val strDescriptionCN: Any? = null,
	val strDescriptionEN: String? = null,
	val strWebsite: String? = null,
	val strYoutube: String? = null,
	val strDescriptionIL: Any? = null,
	val idCup: String? = null,
	val strComplete: String? = null,
	val strLocked: String? = null,
	val idLeague: String? = null,
	val idSoccerXML: String? = null,
	val strTrophy: String? = null,
	val strBadge: String? = null,
	val strTwitter: String? = null,
	val strDescriptionHU: Any? = null,
	val strGender: String? = null,
	val strLeagueAlternate: String? = null,
	val strDescriptionSE: Any? = null,
	val strNaming: String? = null,
	val strDivision: String? = null,
	val strDescriptionJP: Any? = null,
	val strFanart1: String? = null,
	val strDescriptionFR: String? = null,
	val strFanart2: String? = null,
	val strFanart3: String? = null,
	val strFacebook: String? = null,
	val strFanart4: String? = null,
	val strCountry: String? = null,
	val strDescriptionNL: Any? = null,
	val strRSS: String? = null,
	val strDescriptionRU: Any? = null,
	val strDescriptionPT: Any? = null,
	val strLogo: String? = null,
	val strDescriptionDE: Any? = null,
	val strDescriptionNO: Any? = null,
	val strLeague: String? = null,
	val strPoster: String? = null,
	val strDescriptionPL: Any? = null
)
